import { describe, expect, it } from 'vitest';
import { RoomRunner } from '../src/room/runner';
import type { Connection, DurableRecord } from '../src/room/types';
import { harness, profile, scope } from './fixtures';

const hash = (digit: string) => digit.repeat(64);
function room(count = 2) {
  const h = harness(), runner = new RoomRunner(null, h.deps);
  expect(runner.create('ABCDE').ok).toBe(true);
  const ids: string[] = [], connections: Connection[] = [];
  for (let index = 0; index < count; index += 1) {
    const credential = hash(String(index + 1));
    const joined = runner.join(profile(`P${index}`), credential); if (!joined.ok) throw new Error(joined.code);
    ids.push(joined.value); const connected = runner.connect(credential); if (!connected.ok) throw new Error(connected.code);
    connections.push(connected.value); runner.ready(connected.value);
  }
  return { h, runner, ids, connections };
}
function start(setup: ReturnType<typeof room>, mode: 'ranked' | 'team' = 'ranked', deadlineMs = 1_000) {
  return setup.runner.intent(setup.connections[0]!, { actionId: 'start', command: { type: 'start', gameId: 'fixture', settings: { mode, deadlineMs } } });
}
function action(setup: ReturnType<typeof room>, index: number, actionId: string, value: number, customScope = scope(setup.runner.record)) {
  return setup.runner.intent(setup.connections[index]!, { actionId, command: { type: 'action', scope: customScope, payload: { type: 'SUBMIT', value } } });
}

describe('provider-independent room runner acceptance', () => {
  it('R01 creates distinct members and recipient-private projections', () => { const s = room(); start(s); const a = s.runner.snapshot(s.connections[0]!)!, b = s.runner.snapshot(s.connections[1]!)!; expect(a.selfId).not.toBe(b.selfId); expect(a.game?.private).not.toEqual(b.game?.private); expect(s.runner.connect('ABCDE').ok).toBe(false); });
  it('R02 reconnects one seat with a fresh generation and retained state', () => { const s = room(); start(s); const old = s.connections[0]!, again = s.runner.connect(hash('1')); expect(again.ok && again.value.playerId).toBe(s.ids[0]); expect(again.ok && again.value.generation).toBeGreaterThan(old.generation); expect(s.runner.snapshot(again.ok ? again.value : old)?.game?.scope).toBeDefined(); });
  it('R03 rejects forged and revoked credentials without private data', () => { const s = room(); expect(s.runner.connect(hash('9')).ok).toBe(false); s.runner.intent(s.connections[0]!, { actionId: 'leave', command: { type: 'leave' } }); expect(s.runner.connect(hash('1')).ok).toBe(false); expect(s.runner.snapshot(s.connections[0]!)).toBeNull(); });
  it('R04 newest socket owns input and keeps one player slot', () => { const s = room(); const newer = s.runner.connect(hash('1')); expect(newer.ok).toBe(true); expect(s.runner.ready(s.connections[0]!).ok).toBe(false); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.players).toHaveLength(2); });
  it('R05 enforces current host authority', () => { const s = room(); const before = s.runner.record; expect(s.runner.intent(s.connections[1]!, { actionId: 'x', command: { type: 'start', gameId: 'fixture', settings: { mode: 'ranked', deadlineMs: 1 } } }).code).toBe('room.hostOnly'); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room).toEqual(before?.kind === 'room' && before.value.room); expect(s.runner.record?.kind === 'room' && s.runner.record.value.game).toBeNull(); });
  it('R06 applies host grace and deterministic transfer without reversion', () => { const s = room(); s.runner.disconnect(s.connections[0]!); s.h.setNow(30_000); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.hostId).toBe(s.ids[0]); s.h.setNow(32_000); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.hostId).toBe(s.ids[1]); s.runner.connect(hash('1')); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.hostId).toBe(s.ids[1]); });
  it('R07 leaving transfers immediately, revokes input and preserves accepted contribution', () => { const s = room(); start(s); action(s, 0, 'tap', 4); s.runner.intent(s.connections[0]!, { actionId: 'leave', command: { type: 'leave' } }); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.hostId).toBe(s.ids[1]); expect(action(s, 0, 'again', 2).code).toBe('auth.staleConnection'); });
  it('R08 cancels recovered safety alarm and aborts once after 60 seconds', () => { const a = room(); start(a, 'ranked', 100_000); a.runner.disconnect(a.connections[1]!); a.h.setNow(60_999); const recovered = a.runner.connect(hash('2')); expect(recovered.ok).toBe(true); expect(a.runner.record?.kind === 'room' && a.runner.record.value.insufficientDeadline).toBeNull(); const b = room(); start(b, 'ranked', 100_000); b.runner.disconnect(b.connections[1]!); b.h.setNow(61_001); b.runner.advance(); expect(b.runner.record?.kind === 'room' && b.runner.record.value.game).toBeNull(); expect(b.runner.record?.kind === 'room' && b.runner.record.value.room.gamesPlayed).toBe(0); });
  it('R09 returns the identical acknowledgement for equal retry and reduces once', () => { const s = room(); start(s); const first = action(s, 0, 'tap', 5), version = s.runner.record?.kind === 'room' ? s.runner.record.value.game?.transition : 0; const retry = action(s, 0, 'tap', 5); expect(retry).toEqual(first); expect(s.runner.record?.kind === 'room' && s.runner.record.value.game?.transition).toBe(version); });
  it('R10 rejects an action-id conflict without changing the original', () => { const s = room(); start(s); action(s, 0, 'tap', 5); expect(action(s, 0, 'tap', 8).code).toBe('intent.conflict'); expect(s.runner.snapshot(s.connections[0]!)?.game?.private).toMatchObject({ own: 5 }); });
  it('R11 rejects scope from an earlier round', () => { const s = room(); start(s); const old = scope(s.runner.record); s.h.setNow(2_001); s.runner.advance(); expect(action(s, 0, 'late', 1, old).code).toBe('game.staleScope'); });
  it('R12 retains the first submission across distinct IDs', () => { const s = room(); start(s); expect(action(s, 0, 'one', 1).accepted).toBe(true); expect(action(s, 0, 'two', 2).code).toBe('action.alreadySubmitted'); expect(s.runner.snapshot(s.connections[0]!)?.game?.private).toMatchObject({ own: 1 }); });
  it('R13 accepts before but processes the deadline at equality', () => { const before = room(); start(before, 'ranked', 100); before.h.setNow(1_099); expect(action(before, 0, 'early', 1).accepted).toBe(true); const equal = room(); start(equal, 'ranked', 100); equal.h.setNow(1_100); expect(action(equal, 0, 'equal', 1).code).toBe('game.staleScope'); });
  it('R14 ignores repeat/stale alarm effects', () => { const s = room(); start(s, 'ranked', 10); s.h.setNow(3_100); s.runner.advance(); s.h.setNow(4_101); s.runner.advance(); const record = s.runner.record; s.runner.advance(); expect(s.runner.record).toEqual(record); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.gamesPlayed).toBe(1); });
  it('R15 restores durable idempotency and overdue deadlines', () => { const s = room(); start(s); const ack = action(s, 0, 'tap', 1); const restarted = new RoomRunner(s.runner.record, s.h.deps); expect(restarted.intent(s.connections[0]!, { actionId: 'tap', command: { type: 'action', scope: scope(s.runner.record), payload: { type: 'SUBMIT', value: 1 } } })).toEqual(ack); s.h.setNow(5_000); restarted.advance(); s.h.setNow(6_001); restarted.advance(); expect(restarted.record?.kind === 'room' && restarted.record.value.room.gamesPlayed).toBe(1); });
  it('R16 serializes completion and abort to one outcome', () => { const s = room(); start(s, 'ranked', 10); s.h.setNow(3_100); s.runner.advance(); s.h.setNow(4_101); s.runner.advance(); expect(s.runner.intent(s.connections[0]!, { actionId: 'abort', command: { type: 'abort' } }).accepted).toBe(false); expect(s.runner.record?.kind === 'room' && Object.keys(s.runner.record.value.awards)).toHaveLength(1); });
  it('R17 awards completion exactly once across reads and advances', () => { const s = room(); start(s, 'ranked', 10); action(s, 0, 'tap', 1); s.h.setNow(3_100); s.runner.advance(); const totals = s.runner.record?.kind === 'room' ? s.runner.record.value.room.totals : {}; s.runner.snapshot(s.connections[0]!); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.totals).toEqual(totals); });
  it('R18 retains frozen roster and historical totals after kick', () => { const s = room(); start(s, 'ranked', 10); action(s, 1, 'tap', 1); s.runner.intent(s.connections[0]!, { actionId: 'kick', command: { type: 'kick', playerId: s.ids[1] } }); s.h.setNow(3_100); s.runner.advance(); s.h.setNow(4_101); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.game?.roster).toEqual(s.ids); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.totals[s.ids[1]!]).toBeGreaterThan(0); });
  it('R19 refuses admission during play and permits it in lobby', () => { const s = room(); start(s); const rejected = s.runner.join(profile('late'), hash('3')); expect(rejected.ok ? '' : rejected.code).toBe('room.inProgress'); s.runner.intent(s.connections[0]!, { actionId: 'abort', command: { type: 'abort' } }); expect(s.runner.join(profile('late'), hash('3')).ok).toBe(true); });
  it('R20 cleanup replaces all private aggregate data with a tombstone', () => { const s = room(); s.h.setNow(8 * 60 * 60_000 + 60 * 60_000 + 2_000); s.runner.advance(); expect(s.runner.record).toEqual({ kind: 'tombstone' }); expect(s.runner.connect(hash('1')).ok).toBe(false); });
  it('R21 close retains a final safe summary and terminally rejects retries', () => { const s = room(); expect(s.runner.intent(s.connections[0]!, { actionId: 'close', command: { type: 'close' } }).accepted).toBe(true); expect(s.runner.snapshot(s.connections[1]!)?.room.status).toBe('closed'); expect(s.runner.create('ABCDE').ok).toBe(false); expect(s.runner.join(profile('late'), hash('3')).ok).toBe(false); expect(s.runner.intent(s.connections[1]!, { actionId: 'later', command: { type: 'leave' } }).code).toBe('room.closed'); });
  it('R22 projections contain only recipient-safe data', () => { const s = room(); start(s); const serialized = JSON.stringify(s.runner.snapshot(s.connections[0]!)); expect(serialized).not.toContain(hash('1')); expect(serialized).not.toContain(`:${s.ids[1]}`); expect(serialized).not.toContain('submissions'); });
  it('R23 versions increase so clients can discard reordered snapshots', () => { const s = room(); const older = s.runner.snapshot(s.connections[0]!)!; s.runner.ready(s.connections[0]!, false); const newer = s.runner.snapshot(s.connections[0]!)!; expect(newer.version).toBeGreaterThan(older.version); const applied = [newer, older].reduce((current, next) => next.version > current.version ? next : current); expect(applied).toEqual(newer); });
  it('R24 accepts game-owned zero, ranked and team awards without raw scores', () => { const zero = room(); start(zero, 'ranked', 10); zero.h.setNow(3_100); zero.runner.advance(); zero.h.setNow(4_101); zero.runner.advance(); expect(zero.runner.record?.kind === 'room' && Object.values(zero.runner.record.value.room.totals)).toEqual([0, 0]); const team = room(); start(team, 'team', 10); team.h.setNow(3_100); team.runner.advance(); team.h.setNow(4_101); team.runner.advance(); expect(team.runner.record?.kind === 'room' && Object.values(team.runner.record.value.room.totals)).toEqual([2, 0]); });

  it('replays game deadlines before a later safety deadline after a late wake', () => { const s = room(); start(s, 'team', 10_000); s.runner.disconnect(s.connections[1]!); s.h.setNow(70_000); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.gamesPlayed).toBe(1); expect(s.runner.record?.kind === 'room' && Object.values(s.runner.record.value.room.totals)).toEqual([2, 0]); });
  it('applies an earlier safety deadline before a later game deadline', () => { const s = room(); start(s, 'team', 70_000); s.runner.disconnect(s.connections[1]!); s.h.setNow(80_000); s.runner.advance(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.game).toBeNull(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.gamesPlayed).toBe(0); });
  it('gives safety priority over an incomplete game deadline at equality', () => { const s = room(); start(s, 'team', 60_000); s.runner.disconnect(s.connections[1]!); s.h.setNow(61_000); s.runner.advance(); /* Equal timestamps use host, safety, game, cleanup priority. */ expect(s.runner.record?.kind === 'room' && s.runner.record.value.game).toBeNull(); expect(s.runner.record?.kind === 'room' && s.runner.record.value.room.gamesPlayed).toBe(0); });

  it('filters normalized whole-token profanity without substring false positives', () => { const s = room(); expect(s.runner.join(profile('ＦＵＣＫ'), hash('3')).ok).toBe(false); expect(s.runner.join(profile('Scunthorpe'), hash('4')).ok).toBe(true); });

  it.each(['__proto__', 'constructor', 'prototype'])('retains accepted %s action IDs across JSON restart', actionId => { const s = room(); const raw = { actionId, command: { type: 'start', gameId: 'fixture', settings: { mode: 'ranked', deadlineMs: 10_000 } } }; const accepted = s.runner.intent(s.connections[0]!, raw); expect(accepted.accepted).toBe(true); const serialized = JSON.parse(JSON.stringify(s.runner.record)) as DurableRecord; const restarted = new RoomRunner(serialized, s.h.deps); expect(restarted.intent(s.connections[0]!, raw)).toEqual(accepted); expect(restarted.intent(s.connections[0]!, { ...raw, command: { ...raw.command, settings: { mode: 'team', deadlineMs: 10_000 } } }).code).toBe('intent.conflict'); });

  it('retains malformed prototype-key action outcomes and detects conflicts', () => { const s = room(); const malformed = { actionId: '__proto__', command: { type: 'leave', extra: 1 } }; const rejected = s.runner.intent(s.connections[0]!, malformed); expect(rejected.code).toBe('intent.invalid'); const serialized = JSON.parse(JSON.stringify(s.runner.record)) as DurableRecord; const restarted = new RoomRunner(serialized, s.h.deps); expect(restarted.intent(s.connections[0]!, malformed)).toEqual(rejected); expect(restarted.intent(s.connections[0]!, { ...malformed, command: { ...malformed.command, extra: 2 } }).code).toBe('intent.conflict'); });

  it('stores arbitrary generated IDs as own durable record keys', () => { const h = harness(); const ids = ['__proto__', 'constructor']; const runner = new RoomRunner(null, { ...h.deps, id: () => ids.shift() ?? 'prototype' }); runner.create('ABCDE'); expect(runner.join(profile('One'), hash('1')).ok).toBe(true); expect(runner.join(profile('Two'), hash('2')).ok).toBe(true); const record = runner.record; expect(record?.kind === 'room' && Object.keys(record.value.memberships)).toEqual(['__proto__', 'constructor']); expect(record?.kind === 'room' && Object.keys(record.value.room.totals)).toEqual(['__proto__', 'constructor']); });
});
